/* eslint-disable no-unused-vars */
import React from "react";
import useCategoryHandlers from "../../hooks/UseCategoryHandler";
import CategorySelector from "../../components/ProductPortfolio/CategorySelector";
import SubcategorySelector from "../../components/ProductPortfolio/SubCategory";
import DetailsRenderer from "../../components/ProductPortfolio/DetailRendrer";


const ProductionPortfolio = () => {
  const categories = [
    {
      name: "Boutique",
      id: "cat1",
      subcategories: [
        {
          name: "Pashmina",
          id: "pashmina",
          details: {
            material_type: [
              "Ultra-Fine Pashmina (10-12 microns)",
              "Fine Pashmina (12-14 microns)",
              "Standard Pashmina (14-16 microns)",
            ],
            quality: [
              "Pure Pashmina (100% Pashmina)",
              "Blend: 50% Pashmina, 50% Cashmere",
              "Blend: 70% Pashmina, 30% Angora",
              "Blend: 80% Pashmina, 20% Vicuna",
              "Blend: 70% Pashmina, 30% Acrylic",
              "Blend: 60% Pashmina, 40% Merino Wool",
              "Blend: 50% Pashmina, 50% Modal",
              "Blend: 60% Pashmina, 40% Tussar Silk",
              "Blend: 50% Pashmina, 50% Polyester",
            ],
            production_process: [
              "Hand Spinning, Hand Weaving",
              "Hand Spinning, Machine Weaving",
              "Machine Spinning, Machine Weaving",
            ],
            product_certifications: [
              "GI Certificate",

              "Responsible Wool Standard (RWS)",
              "Blockchain Traceability",
              "None",
            ],

            type_of_weaving: [
              "Twill Weave ",
              "Diamond Weave ",
              "Herringbone Weave",
              "Jacquard Weave",
              "Plain Weave",
              "Honeycomb Weave",
            ],
            dye_types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            product_line_size: [
              "Shawls  (203 cm x 102 cm)",
              "Stoles  (178 cm x 76 cm)",
              "Scarves (152 cm x 51 cm)",
              "Wraps (229 cm x 89 cm)",
              "Ponchos (86 cm x 102 cm) ",
              "Sarees (550 cm x 115 cm)",
            ],
            color_shades: [
              "Natural Shades",
              "Classic Neutrals",
              "Pastel Shades",
              "Jewel Tones",
              "Earthy Tones",
              "Bold and Vibrant Shades",
              "Metallic Shades",
              "Dual-Tone and Gradient Shades",
              "Soft Whites and Off-Whites",
            ],
            embellishments: [
              "Full Dense Embroidery",
              "Full Border Embroidery",
              "Allover Embroidery",
              "Motif Embroidery",
              "End Panel Embroidery",
              "Narrow Border Embroidery",
              "Wide Border Embroidery",
              "Dense Allover Embroidery",
              "Double Border Embroidery",
              "Reverse Embroidery",
              "Metal Thread Embroidery",
              "Papier Mâché Embroidery",
            ],
          },
        },
        {
          name: "Cashmere",
          id: "cashmere",
          details: {
            material_type: [
              "Ultra-Fine Cashmere (13-15 microns)",
              "Fine Cashmere (15-17 microns)",
              "Standard Cashmere (17-19 microns)",
            ],
            quality: [
              "Pure Cashmere (100% Cashmere)",
              "Blend: 50% Cashmere, 50% Pashmina",
              "Blend: 70% Cashmere, 30% Angora",
              "Blend: 80% Cashmere, 20% Vicuna",
              "Blend: 70% Cashmere, 30% Acrylic",
              "Blend: 60% Cashmere, 40% Merino Wool",
              "Blend: 50% Cashmere, 50% Modal",
              "Blend: 60% Cashmere, 40% Tussar Silk",
              "Blend: 50% Cashmere, 50% Polyester",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Hand Spinning, Machine Weaving",
              "Machine Spinning, Machine Weaving",
            ],
            Product_Certifications: [
              "Responsible Wool Standard (RWS)",
              "Blockchain Traceability",
              "None",
            ],
            Type_of_Weaving: [
              "Twill Weave ",
              "Diamond Weave ",
              "Herringbone Weave",
              "Jacquard Weave",
              "Plain Weave",
              "Honeycomb Weave",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Shawls  (203 cm x 102 cm)",
              "Stoles  (178 cm x 76 cm)",
              "Scarves (152 cm x 51 cm)",
              "Wraps (229 cm x 89 cm)",
              "Ponchos (86 cm x 102 cm) ",
              "Sarees (550 cm x 115 cm)",
            ],
            Color_Shades: [
              "Natural Shades",
              "Classic Neutrals",
              "Pastel Shades",
              "Jewel Tones",
              "Earthy Tones",
              "Bold and Vibrant Shades",
              "Metallic Shades",
              "Dual-Tone and Gradient Shades",
              "Soft Whites and Off-Whites",
            ],
            Embellishments: [
              "Full Dense Embroidery",
              "Full Border Embroidery",
              "Allover Embroidery",
              "Motif Embroidery",
              "End Panel Embroidery",
              "Narrow Border Embroidery",
              "Wide Border Embroidery",
              "Dense Allover Embroidery",
              "Double Border Embroidery",
              "Reverse Embroidery",
              "Metal Thread Embroidery",
              "Papier Mâché Embroidery",
            ],
          },
        },
        {
          name: "Kani",
          id: "kani",
          details: {
            material_type: [
              "Ultra-Fine Pashmina (10-12 microns)",
              "Fine Pashmina (12-14 microns)",
              "Standard Pashmina (14-16 microns)",
            ],
            quality: [
              "Pure Pashmina (100% Pashmina)",
              "Blend: 50% Pashmina, 50% Cashmere",
              "Blend: 60% Pashmina, 40% Tussar Silk",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Hand Spinning, Machine Weaving",
              "Machine Spinning, Machine Weaving",
            ],
            Product_Certifications: [
              "GI Certificate",

              "Responsible Wool Standard (RWS)",
              "Blockchain Traceability",
              "None",
            ],
            Design_Pattern_Types: [
              "Paisley",
              "Floral Patterns",
              "Geometric Patterns",
              "Tree of Life",
              "Abstract Patterns",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Shawls  (203 cm x 102 cm)",
              "Stoles  (178 cm x 76 cm)",
              "Scarves (152 cm x 51 cm)",
              "Wraps (229 cm x 89 cm)",
              "Ponchos (86 cm x 102 cm) ",
              "Sarees (550 cm x 115 cm)",
            ],
            Color_Shades: [
              "Traditional Kani Colors",
              "Classic Neutrals",
              "Pastel Shades",
              "Jewel Tones",
              "Earthy Tones",
              "Bold and Vibrant Shades",
              "Metallic Shades",
            ],
            Embellishments: ["Kani Tassels", "Traditional Knotting"],
          },
        }, //Dining & Serving Ware
        {
          name: "Silk",
          id: "silk",
          details: {
            material_type: [
              "Mulberry Silk",
              "Tussar Silk",
              "Eri Silk",
              "Muga Silk",
              "Raw Silk",
              "Organza Silk",
            ],
            quality: [
              "Pure Silk (100% Silk)",
              "Blend: 50-70% Silk, 30-50% Cotton",
              "Blend: 50-70% Silk, 30-50% Wool",
              "Blend: 50-70% Silk, 30-50% Cashmere",
              "Blend: 50-70% Silk, 30-50% Polyester",
              "Blend: 50-70% Silk, 30-50% Linen",
              "70% Silk, 30% Bamboo",
              "Blend: 60-70% Silk, 30-40% Modal",
              "Blend: 60% Silk, 40% Tussar Silk",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Hand Spinning, Machine Weaving",
              "Machine Spinning, Machine Weaving",
            ],
            Product_Certifications: ["Badges", "Blockchain Traceability"],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Paisley",
              "Floral Patterns",
              "Geometric Patterns",
              "Tree of Life",
              "Abstract Patterns",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Shawls - 203 cm x 102 cm",
              "Stoles - 178 cm x 76 cm",
              "Scarves - 152 cm x 51 cm",
              "Wraps - 229 cm x 89 cm",
              "Ponchos - 86 cm x 102 cm",
              "Sarees - 550 cm x 115 cm",
              "Dupattas - 254 cm x 102 cm",
            ],
            Color_Shades: [
              "Traditional Kani Colors",
              "Classic Neutrals",
              "Pastel Shades",
              "Jewel Tones",
              "Earthy Tones",
              "Bold and Vibrant Shades",
              "Metallic Shades",
            ],
            Embellishments: [
              "End Panel Embroidery",
              "Metal Thread Embroidery",
              "Narrow Border Embroidery",
            ],
          },
        },
        {
          name: "Sarongs",
          id: "sarongs",
          details: {
            material_type: ["Pashmina", "Cashmere", "Cotton", "Silk", "Linen"],
            quality: [
              "Pure Pahmina",
              "Pure Cashmere",
              "Khadi Cotton",
              "Pure Silk",
              "Handwoven Linen",
            ],
            production_process: ["Hand Weaving", "Machine Weaving"],

            design_pattern_types: [
              "Floral Motifs",
              "Geometric Patterns",
              "Abstract Art",
              "Cultural and Traditional Designs",
            ],
            dye_types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
            ],

            product_line_size: [
              "Long Sarong - 152-178 cm",
              "Short Sarong - 102-127 cm",
              "Wrap Skirt Style - 127-152 cm",
            ],

            color_shades: [
              "Classic Neutrals",
              "Traditional Tones",
              "Pastel Shades",
              "Bright Bold Shades",
            ],

            embellishments: [
              "Beaded Borders",
              "Embroidered Panels",
              "Fringe Detailing",
              "Tassels",
            ],
          },
        },
        {
          name: "Bags & Purses",
          id: "bags",
          details: {
            material_type: [
              "Wool",
              "Silk",
              "Cotton",
              "Leather",
              "Canvas",
              "Jute",
              "Velvet",
            ],
            quality: [
              "Pure Wool",
              "Silk-Cotton Blend",
              "Embroidered Leather",
              "Kashmiri Pashmina",
            ],
            Production_Process: ["Handcrafted", "Machine Stitching"],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Chain Stitch Embroidery",
              "Papier Mâché Inspired Embroidery",
              "Sozni Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Paisley",
              "Floral Patterns",
              "Geometric Patterns",
              "Traditional Kashmiri Motifs",
              "Abstract Patterns",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Clutch - 20 cm x 10 cm",
              "Shoulder Bag - 30 cm x 25 cm x 10 cm",
              "Tote Bag - 40 cm x 35 cm x 12 cm",
              "Sling Bag - 20 cm x 25 cm x 5 cm",
              "Backpack - 40 cm x 30 cm x 15 cm",
              "Coin Purse - 10 cm x 8 cm",
            ],
            Color_Shades: [
              "Classic Neutrals",
              "Traditional Kashmiri Colors",
              "Bright and Bold Shades",
              "Pastel Shades",
              "Metallic Shades",
            ],
            Embellishments: [
              "Tassels",
              "Mirror Work",
              "Beaded Detailing",
              "Sequins",
              "Metallic Threads",
            ],
          },
        },
        {
          name: "Jackets",
          id: "jackets",
          details: {
            material_type: [
              "Pashmina",
              "Cashmere",
              "Silk",
              "Cotton",
              "Velvet",
              "Leather",
            ],
            quality: [
              "Pure Pashmina",
              "Pure Cashmere",
              "Wool-Cotton Blend",
              "Silk-Wool Blend",
              "Embossed or Embroidered Leather",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Machine Weaving",
              "Handcrafted",
              "Machine Stitching",
            ],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Sozni Embroidery",
              "Tilla Work (Gold/Silver Thread Embroidery)",
              "Chain Stitch Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Paisley",
              "Floral Patterns",
              "Geometric Patterns",
              "Traditional Kashmiri Motifs",
              "Minimalist Designs",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Short Jacket - 61-66 cm",
              "Long Coat - 91-102 cm",
              "Overcoat - 107-122 cm",
              "Bomber Jacket - 56-61 cm",
              "Blazer - 71-76 cm",
            ],
            Color_Shades: [
              "Classic Neutrals",
              "Traditional Kashmiri Colors",
              "Bright and Bold Shades",
              "Pastel Shades",
              "Metallic Shades",
            ],

            Size_Available: [
              "Small (S)",
              "Medium (M)",
              "Large (L)",
              "Extra Large (XL)",
              "Custom Fit",
            ],
            Embellishments: [
              "Tilla Borders",
              "Embroidered Cuffs and Collars",
              "Mirror Work",
              "Beaded Detailing",
              "Sequins",
            ],
          },
        },
        {
          name: "Kaftans",
          id: "kaftans",
          details: {
            material_type: [
              "Pashmina",
              "Silk",
              "Cotton",
              "Linen",
              "Velvet",
              "Chiffon",
            ],
            quality: [
              "Pure Pashmina",
              "Pure Silk",
              "Cotton-Linen Blend",
              "Embroidered Velvet",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Machine Weaving",
              "Handcrafted",
              "Machine Stitching",
            ],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Sozni Embroidery",
              "Tilla Work (Gold/Silver Thread Embroidery)",
              "Chain Stitch Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Floral Patterns",
              "Paisley",
              "Geometric Patterns",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Long Kaftan - 127-137 cm",
              "Short Kaftan - 102-112 cm",
              "Kimono Style Kaftan - 122-132 cm",
            ],
            Color_Shades: [
              "Classic Neutrals",
              "Traditional Kashmiri Colors",
              "Bright and Bold Shades",
              "Pastel Shades",
              "Metallic Shades",
            ],

            Size_Available: [
              "Small (S)",
              "Medium (M)",
              "Large (L)",
              "Extra Large (XL)",
              "Custom Fit",
            ],
            Embellishments: [
              "Tilla Borders",
              "Embroidered Sleeves",
              "Mirror Work",
              "Beaded Detailing",
              "Sequins",
            ],
          },
        },
        {
          name: "Kurtas",
          id: "kurtas",
          details: {
            material_type: [
              "Wool",
              "Silk",
              "Cotton",
              "Linen",
              "Velvet",
              "Khadi",
            ],
            quality: [
              "Pure Wool",
              "Pure Silk",
              "Cotton-Linen Blend",
              "Handwoven Khadi",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Machine Weaving",
              "Handcrafted",
              "Machine Stitching",
            ],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Sozni Embroidery",
              "Tilla Work (Gold/Silver Thread Embroidery)",
              "Chain Stitch Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Floral Patterns",
              "Paisley",
              "Geometric Patterns",
              "Traditional Kashmiri Motifs",
              "Minimalist Designs",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Long Kaftan - 127-137 cm",
              "Short Kaftan - 102-112 cm",
              "Kimono Style Kaftan - 122-132 cm",
            ],
            Color_Shades: [
              "Classic Neutrals",
              "Traditional Kashmiri Colors",
              "Bright and Bold Shades",
              "Pastel Shades",
              "Metallic Shades",
            ],

            Size_Available: [
              "Small (S)",
              "Medium (M)",
              "Large (L)",
              "Extra Large (XL)",
              "Custom Fit",
            ],
            Embellishments: [
              "Tilla Borders",
              "Embroidered Sleeves",
              "Mirror Work",
              "Beaded Detailing",
              "Sequins",
            ],
          },
        },
        {
          name: "Pherans",
          id: "pherans",
          details: {
            material_type: [
              "Wool",
              "Cashmere",
              "Silk",
              "Cotton",
              "Khadi",
              "Tweed",
              "Blazer Fabric",
              "Funnel Fabric",
            ],
            quality: [
              "Pure Wool",
              "Pure Cashmere",
              "Wool-Cotton Blend",
              "Handwoven Khadi",
              "Tweed Quality",
              "Blazer Quality",
            ],
            Production_Process: [
              "Hand Spinning, Hand Weaving",
              "Machine Weaving",
              "Handcrafted",
              "Machine Stitching",
            ],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Sozni Embroidery",
              "Tilla Work (Gold/Silver Thread Embroidery)",
              "Chain Stitch Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Floral Patterns",
              "Paisley",
              "Geometric Patterns",
              "Traditional Kashmiri Motifs",
              "Minimalist Designs",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Long Pheran - 114-127 cm",
              "Short Pheran - 91-102 cm",
            ],
            Color_Shades: [
              "Classic Neutrals",
              "Traditional Kashmiri Colors",
              "Bright and Bold Shades",
              "Pastel Shades",
              "Metallic Shades",
            ],

            Size_Available: [
              "Small (S)",
              "Medium (M)",
              "Large (L)",
              "Extra Large (XL)",
              "Custom Fit",
            ],
            Embellishments: [
              "Tilla Borders",
              "Embroidered Sleeves",
              "Mirror Work",
              "Beaded Detailing",
              "Sequins",
            ],
          },
        },
        {
          name: "Jewelry",
          id: "jewelry",
          details: {
            material_type: [
              "Silver",
              "Gold",
              "Copper",
              "Brass",
              "Semi-precious Stones",
              "Pearls",
              "Enamel",
            ],
            quality: [
              "Pure Silver",
              "22K Gold",
              "Brass with Silver Plating",
              "Handcrafted Silver",
            ],
            Production_Process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            Jewerly_Types: [
              "Necklaces",
              "Earrings",
              "Bracelets",
              "Rings",
              "Bangles",
              "Anklets",
            ],
            Product_Certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            Embroidery_Types: [
              "Aari Work",
              "Sozni Embroidery",
              "Tilla Work (Gold/Silver Thread Embroidery)",
              "Chain Stitch Embroidery",
              "Zardozi Embroidery",
            ],
            Type_of_Weaving: [
              "Satin Weave",
              "Twill Weave",
              "Plain Weave",
              "Jacquard Weave",
              "Organza Weave",
              "Brocade Weave",
              "Crepe Weave",
              "Chiffon Weave",
              "Georgette Weave",
            ],
            Design_Pattern_Types: [
              "Traditional Kashmiri Motifs",
              "Floral Patterns",
              "Geometric Designs",
              "Filigree Work",
              "Kundan Work",
            ],

            Finishing_Techniques: [
              "Polished Finish",
              "Matte Finish",
              "Oxidized Finish",
              "Hammered Finish",
              "Enamel Work",
            ],
            Dye_Types: [
              "Natural-Dyed",
              "Vegetable-Dyed",
              "Chemical-Dyed",
              "Acid-Dyed",
              "Eco-Dyed",
              "Azo-Free Dyed",
              "Tie-Dyed",
              "Ombre-Dyed",
              "Hand-Painted or Brush-Dyed",
            ],
            Product_Line_Size: [
              "Necklaces - 41-51 cm",
              "Earrings - 2.5-7.5 cm",
              "Bracelets - 18-20 cm",
              "Rings - Sizes: 6-10 (US Sizes)",
              "Bangles - 6.5-7.5 cm",
              "Anklets - 23-28 cm",
            ],
            Color_Shades: [
              "Classic Metallics",
              "Gemstone Colors",
              "Enamel Colors",
            ],

            Size_Available: [
              "Small (S)",
              "Medium (M)",
              "Large (L)",
              "Extra Large (XL)",
              "Custom Fit",
            ],
            Embellishments: [
              "Filigree Work",
              "Stone Inlays",
              "Enamel Detailing",
              "Beading",
            ],
          },
        },
      ],
    },
    {
      name: "Interior Décor",
      id: "cat2",
      subcategories: [
        {
          name: "Papier-Mache",
          id: "papierMachie",
          details: {
            material_type: ["Papier-Mâché", "Wood", "Fabric", "Metal"],
            quality: [
              "Handcrafted Papier-Mâché",
              "Premium Quality Finish",
              "Eco-Friendly Materials",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Hand-Painted",
              "Varnished",
              "Gold/Silver Leaf Application",
              "Textured Finishes",
            ],
            product_type_and_size:[
              "Wall Art Decorative Panels  24\" x 36\""
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",

              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: ["Mirror Work", "Metallic Thread"],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Tapestry",
          id: "tapestry",
          details: {
            material_type: ["Wool", "Silk", "Cotton", "Blended Fabrics"],
            quality: [
              "Handcrafted",
              "Premium Quality Finish",
              "Eco-Friendly Materials",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Fringing",
              "Backing",
              "Binding",
              "Lining",
              "Mounting",
              "Stiffening",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: [
              "Mirror Work",
              "Beaded Work",
              "Zardozi Embroidery",
              "Sequins",
            ],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Jeweled Wall Hangings",
          id: "jeweled",
          details: {
            material_type: ["Fabric (Silk, Cotton)", "Metal"],
            quality: [
              "Handcrafted",
              "Premium Quality Finish",
              "Eco-Friendly Materials",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Fringing",
              "Backing",
              "Binding",
              "Lining",
              "Mounting",
              "Stiffening",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: [
              "Mirror Work",
              "Beaded Work",
              "Zardozi Embroidery",
              "Sequins",
              "Precious and Semi-Precious Metals",
            ],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        }, //Office Accessories
        {
          name: "Office Accessories",
          id: "officeAcc",
          details: {
            material_type: [
              "Wood",
              "Papier-Mâché",
              "Metal",
              "Fabric",
              "Leather",
            ],
            quality: [
              "Handcrafted",
              "Eco-Friendly Materials",
              "Premium Quality Finish",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Hand-Painted",
              "Varnished",
              "Textured Finishes",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: ["Mirror Work", "Metallic Thread", "Carvings"],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Room Divider Screens",
          id: "roomDividerSec",
          details: {
            material_type: ["Wood", "Papier-Mâché", "Fabric", "Metal"],
            quality: [
              "Handcrafted Wood",
              "Eco-Friendly Materials",
              "Premium Quality Finish",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Hand-Painted",
              "Lacquered",
              "Varnished",
              "Textured Finishes",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: ["Mirror Work", "Metallic Thread", "Carvings"],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        }, //Sofa and Cushion Covers  Sofa and Cushion Covers
        {
          name: "Sofa and Cushion Covers",
          id: "sofaCushion",
          details: {
            material_type: ["Cotton", "Silk", "Wool", "Velvet"],
            quality: [
              "100% Cotton",
              "Pure Silk",
              "Merino Wool",
              "Handcrafted Fabrics",
              "Eco-Friendly Materials",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Hand-Painted",
              "Embroidered",
              "Screen-Printed",
              "Block-Printed",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: ["Embroidery", "Lace Detailing", "Appliqué Work"],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Bed Linens",
          id: "bedLinens",
          details: {
            material_type: ["Cotton", "Silk", "Wool", "Linen"],
            quality: [
              "100% Cotton",
              "Pure Silk",
              "Merino Wool",
              "Handcrafted Fabrics",
              "Eco-Friendly Materials",
            ],
            production_process: [
              "Handcrafted",
              "Machine-Made",
              "Traditional Techniques",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
              "Abstract Designs",
              "Custom Designs",
            ],
            finishing_techniques: [
              "Hand-Painted",
              "Embroidered",
              "Screen-Printed",
              "Block-Printed",
            ],
            certifications: [
              "Handcrafted Badge",
              "Eco-Friendly Certification",
              "Authenticity Certificate",
            ],
            color_shades: [
              "Classic Neutrals",
              "Bright and Bold Colors",
              "Pastel Shades",
            ],
            embellishments: ["Embroidery", "Lace Detailing", "Appliqué Work"],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
      ],
    },
    {
      name: "Dining & Serving Ware",
      id: "cat3",
      subcategories: [
        { name: " Papermachieware", id: " papermachieware" },
        { name: "Walnutware", id: "walnutware" }, //Silverware
        { name: "Silverware", id: "silverware" },
        { name: "Copperware", id: "copperware" },
      ],
    },
    {
      name: "Rugs and Carpets",
      id: "cat4",
      subcategories: [
        {
          name: "Rugs and Carpets",
          id: "rugs",
          details: {
            material_type: ["Silk on Silk", "Silk on Wool", "Wool on Cotton"],
            production_process: ["Hand-Knotted", "Hand-Tufted", "Machine-Made"],
            knot_per_inch: [
              "60-100 KPSI",
              "100-300 KPSI",
              "300-600 KPSI",
              "400-800 KPSI",
              "600-800 KPSI",
            ],
            design_pattern_types: [
              "Floral Patterns",
              "Geometric Designs",
              "Traditional Kashmiri Motifs",
            ],
            certifications: [
              "Geographical Indication (GI) Tag",
              "Eco-Friendly Certification",
            ],
            color_shades: [
              // "Ivory",
              // "Beige",
              // "Gray",
              // "Black",
              // "Navy Blue",
              // "Brown",
              // "Blush Pink",
              // "Mint Green",
              // "Lavender",
              // "Rust",
              // "Terracotta",
              // "Olive Green",
              // "Scarlet Red",
              // "Royal Blue",
              // "Deep Purple",
              // "Pearl White",
              // "Antique White",
              // "Cream",
              "Ivory",
              "Beige",
              "Gray",
              "Black",
              "Navy Blue",
              "Brown",
              "Blush Pink",
              "Mint Green",
              "Lavender",
              "Rust",
              "Terracotta",
              "Olive Green",
              "Scarlet Red",
              "Royal Blue",
              "Deep Purple",
              "Pearl White",
              "Antique White",
              "Cream",
              "Emerald Green",
              "Ruby Red",
              "Turquoise",
              "Charcoal",
              "Mahogany",
              "Soft Peach",
              "Light Lavender",
              "Sky Blue",
              "Mustard Yellow",
              "Coral",
              "Aqua",
              "Sunshine Yellow",
              "Soft Pink",
              "Light Mint",
              "Red",
              "Orange",
              "Sand",
              "Snow White",
              "Tan",
              "Deep Blue",
              "Light Pink",
              "Baby Blue",
              "Amethyst Purple",
              "Sapphire Blue",
              "Dark Hues",
              "Wine/Burgundy",
              "Forest Green",
              "Espresso",
              "Earthy Tones",
              "Natural Shades",
              "Jewel Tones",
              "Deep Hues",
            ],
            dimensions: [
              "2' x 3' (60 cm x 90 cm)",
              "2' x 6' (60 cm x 180 cm)",
              "2' x 8' (60 cm x 240 cm)",
              "3' x 5' (90 cm x 150 cm)",
              "3' x 10' (90 cm x 300 cm)",
              "4' x 4' (120 cm x 120 cm)",
              "4' x 6' (120 cm x 180 cm)",
              "5' x 7' (150 cm x 210 cm)",
              "6' x 9' (180 cm x 270 cm)",
              "7' x 10' (210 cm x 300 cm)",
              "8' x 10' (240 cm x 300 cm)",
              "9' x 12' (270 cm x 360 cm)",
              "10' x 14' (300 cm x 420 cm)",
              "12' x 18' (360 cm x 540 cm)",
            ],
            packaging: [
              "Custom-fit Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Carpet Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Namda Embroidery Rugs",
          id: "namda",
          details: {
            material_type: ["Wool", "Wool-Cotton Blends"],
            production_process: ["Handcrafted"],
            design_pattern_types: ["Traditional Kashmiri Motifs"],
            dimensions: [
              "4' x 6' (120 cm x 180 cm)",
              "5' x 7' (150 cm x 210 cm)",
              "3' x 5' (90 cm x 150 cm)",
            ],
            product_certifications: [
              "FSC Certification",
              "GI",
              "Block Chain",

              "PEFC",
              "SFI",
              "None",
            ],
            color_shades: [
              "Terracotta",
              "Olive Green",
              "Natural Shades",
              "Jewel Tones",
              "Deep Hues",
            ],
            finishing_techniques: [
              "Fringed Edges",
              "Bound Edges",
              "Double-Sided Finish",
            ],
            weight: ["Light", "Medium", "Heavy"],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Product Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
      ],
    },
    {
      name: "Furniture",
      id: "cat5",
      subcategories: [
        {
          name: "Walnut Wood Carving Furniture",
          id: "walnut",
          details: {
            material_type: [
              "Kashmiri Walnut Wood - Grade A",
              "Kashmiri Walnut Wood - Grade B",
              "Kashmiri Walnut Wood - Grade C",
            ],
            production_process: ["Hand-Carved", "Machine-Made"],
            design_carvings: [
              "Intricate Hand-Carving",
              "Relief Carving",
              "Inlay Work",
            ],
            scale_of_carving: [
              "High Relief Carving",
              "Low Relief Carving",
              "Flat Carving",
            ],
            design_pattern_types: [
              "Traditional Kashmiri Motifs",
              "Geometric Patterns",
              "Contemporary Designs",
            ],
            product_name_and_dimensions: [
              "King Size Bed: 6.5' x 6.5'",
              "Queen Size Bed: 5' x 6.5'",
              "Full Size Bed: 4.5' x 6.5'",
              "Twin Size Bed: 3' x 6.5'",
              "Nightstand: 2' x 1.5'",
              "Storage Bed (King): 6.5' x 6.5'",
              "Coffee Table: 4' x 2'",
              "Side Table: 2' x 2'",
              "Media Cabinet: 5' x 2'",
              "Display Cabinet: 6' x 3'",
              "Ottoman: 2' x 2'",
              "Sofa Table: 5' x 1.5'",
              "Dining Table: 6' x 3'",
              "Dining Set (Table + 4 Chairs): Table 5' x 3'",
              "Buffet Table: 6' x 1.5'",
              "Storage Bench: 4' x 1.5'",
              "Wine Rack: 3' x 1.5'",
              "Writing Desk: 5' x 2.5'",
              "Hallway Table: 4' x 1'",
              "Console Table: 5' x 1.5'",
              "End Table: 3' x 2'",
              "Pedestal Table: 3' x 3'",
              "Armchair: Width 2.5'",
              'Bar Stool: Height 30"',
            ],
            certifications: [
              "Geographical Indication (GI) Tag",
              "Eco-Friendly Certification",
            ],
            color_shades: ["Dark Walnut", "Light Walnut", "Medium Walnut"],
            finishings: ["Matte Finish", "Glossy Finish", "Semi-Gloss Finish"],
            stain: ["Antique Stain", "Cherry Stain"],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Crewel Upholstered Furniture",
          id: "crewel",
          details: {
            material_type: ["Crewel-embroidered fabric"],
            production_process: ["Hand embroidery techniques"],
            design_pattern_types: [
              "Floral Motifs",
              "Nature-Inspired Designs",
              "Geometric Patterns",
            ],
            finishing_techniques: [
              "Hand-stitched edges",
              "Lining and backing finishes",
            ],
            certifications: ["Handcrafted Artisanship Certification"],
            color_shades: ["Vibrant Wool Colors", "Earthy Tones"],
            product_name_and_dimensions: [
              "Crewel-Embroidered Sofa: 6' long",
              "Crewel-Embroidered Armchair: 3' wide",
              "Crewel Footstool: 2' x 1.5'",
              "Crewel-Embroidered Bench: 4' long",
              "Crewel Ottoman: 2' x 2'",
              "Crewel Table Runner: 6' long",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        }, //Wicker Furniture
        {
          name: "Wicker Furniture",
          id: "wicker",
          details: {
            material_type: ["Rattan", "Reed", "Bamboo"],
            production_process: [
              "Hand-weaving techniques",
              "Natural material treatment",
            ],
            design_pattern_types: ["Traditional Weaves", "Contemporary Styles"],
            finishing_techniques: ["Natural Sealing", "Protective Coatings"],
            certifications: ["Eco-Friendly Certification"],
            color_shades: [
              "Natural Brown",
              "Painted Finishes",
              "Whitewash",
              "Pastel Shades",
            ],
            product_name_and_dimensions: [
              "Lounge Chair: 3' high, 2.5' wide, 2' deep",
              "Coffee Table: 4' long, 2' wide, 1.5' high",
              "Storage Basket: 2' diameter, 1.5' high",
              "Side Table: 2.5' high, 2' diameter",
              "Dining Chair: 3' high, 2' wide, 1.5' deep",
              "Ottoman: 2' x 2' , 1.5' high",
              "Serving Tray: 2' x 1', 2\" high",
              "Bench: 5' long, 1.5' wide, 2' high",
              "Planter: 1.5' height, 2' diameter",
              "Bar Stool: 3' high, 1.5' wide, 1.5' deep",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Room Dividers",
          id: "roomDivider",
          details: {
            material_type: ["Wood", "Fabric", "Wicker"],
            production_process: ["Handcrafted joinery", "Assembly techniques"],
            design_pattern_types: [
              "Carved Designs",
              "Fabric Panels",
              "Geometric Shapes",
              "Floral Motifs",
            ],
            finishing_techniques: ["Staining", "Painting", "Natural Sealing"],
            certifications: [
              "Handcrafted Quality Certification",
              "Eco-Friendly Certification",
            ],
            color_shades: [
              "Natural Wood Tones",
              "Bold Fabric Colors",
              "Soft Pastels",
              "Dark Stains",
            ],
            product_name_and_dimensions: [
              "Wooden Carved Room Divider: 6' x 3'",
              "Fabric Room Divider (Crewel): 5' x 3'",
              "Portable Room Divider: 4' x 6'",
              "Wicker Room Divider: 5' x 3'",
              "Folding Room Divider: 6' x 2'",
              "Decorative Screen Divider: 5' x 5'",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
      ],
    },

    {
      name: "Ceiling Treatment",
      id: "cat6",
      subcategories: [
        {
          name: "Ceiling Treatment (Khatamband)",
          id: "ceiling",
          details: {
            material_type: [
              "Kashmiri Walnut Wood",
              "Deodar Cedar",
              "Fir Wood",
              "Pine Wood",
              "Local Softwoods",
            ],
            production_process: ["Handcrafted Techniques", "Joinery Methods"],
            design_pattern_types: [
              "Geometric Patterns - Kaat",
              "Floral Motifs - Gulzar",
              "Traditional Kashmiri Motifs - Dastakari",
              "Abstract Patterns - Nazar",
              "Inlaid Patterns - Kashida",
              "Border Designs - Chowk",
              "Three-Dimensional Effects - Udaak",
              "Regional Variations - Rangrez",
            ],
            finishing_techniques: ["Natural Finish", "Lacquer Finish"],
            product_certifications: [
              "FSC Certification",
              "GI",
              "Block Chain",

              "PEFC",
              "SFI",
              "None",
            ],
            color_shades: ["Natural Wood Tones", "Stained Finishes"],
            embellishments: ["Papier-Mâché", "Carving"],
            product_name_and_dimensions: [
              "Khatamband Ceiling Panel: 4' x 4'",
              "Khatamband Decorative Strip: 3' long",
              "Khatamband Ceiling Tile: 2' x 2'",
              "Khatamband Cornice: 5' long",
              "Khatamband Center Medallion: 3' diameter",
              "Khatamband Wall Panel: 4' x 2'",
              "Khatamband Column Wrap: 8' height",
              "Khatamband Light Fixture Cover: 2' x 2'",
              "Khatamband Frame for Windows: 3' x 5'",
              "Khatamband Ceiling Beam Cover: 6' long",
              "Khatamband Decorative Archway: 5' x 3'",
              "Khatamband Ceiling Medallion: 2.5' diameter",
            ],
            installation_services: [
              "Site Assessment ",
              "Preparation ",
              "Cutting & Fitting ",
              "Attachment ",
              "Finishing Touches ",
              "Final Inspection ",
            ],
            service_options: [
              "Residential Installation",
              "Commercial Installation",
              "Custom Design Services ",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
            Passport_Status_for_Vendor_Staff_Required_for_international_projects:
              ["Clean Passport", "Passport Under Process", "Not Ready"],
          },
        },
      ],
    },

    {
      name: "Window Treatment",
      id: "cat7",
      subcategories: [
        {
          name: "Pinjrakari - Kashmir Lattice Work",
          id: "pinjrakari",
          details: {
            material_type: [
              "Silver Fir Wood",
              "Blue Pine Wood",
              "Walnut Wood",
              "Cedar (Deodar) Wood",
            ],

            production_process: [
              "Handcrafted Techniques",
              "Traditional Joinery",
            ],
            design_pattern_types: [
              "Crossing Patterns (Intersecting lines)",
              "Checkerboard (Alternating grid pattern)",
            ],
            design_shapes: ["Triangle", "Square", "Hexagon"],
            design_carvings: [
              "Ornamental Carvings",
              "Abstract Geometric Carvings",
            ],
            finishing_techniques: [
              "Natural Finish ",
              "Lacquer Finish ",
              "Stained Finish ",
            ],
            color_shades: ["Natural Wood Tones ", "Dark Stains "],
            embellishments: ["Inlaid Designs "],
            dimensions: [
              "Window Panel (120 cm x 180 cm)",
              "Room Divider (180 cm x 120 cm)",
              "Door Panel (210 cm x 90 cm)",
              "Ceiling Panel (60 cm x 60 cm)",
              "Wall Panel (120 cm x 60 cm)",
              "Balcony Railing (90 cm x 150 cm)",
              "Staircase Railing (120 cm x 90 cm)",
              "Decorative Screen (150 cm x 90 cm)",
              "Ventilation Screen (60 cm x 60 cm)",
              "Archway Panel (150 cm x 120 cm)",
              "Sliding Door Panel (213 cm x 106 cm)",
              "Room Divider - Hinges (180 cm x 150 cm)",
              "Decorative Wall Insert (90 cm x 90 cm)",
              "Cabinet Doors (180 cm x 75 cm per panel)",
              "Tabletop Screen (60 cm x 60 cm)",
              "Fireplace Screen (90 cm x 120 cm)",
              "Window Shutters (120 cm x 60 cm / shutter)",
              "Headboard Panel (180 cm x 90 cm)",
              "Outdoor Privacy Screen (180 cm x 180 cm)",
              "Staircase Baluster (90 cm x 30 cm / panel)",
            ],
            product_certifications: [
              "FSC Certification",
              "GI",
              "Block Chain",

              "PEFC",
              "SFI",
              "None",
            ],
            installation_services: [
              "Site Assessment ",
              "Preparation ",
              "Cutting & Fitting ",
              "Attachment ",
              "Finishing Touches ",
              "Final Inspection ",
            ],
            service_options: [
              "Residential Installation",
              "Commercial Installation",
              "Custom Design Services ",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
            Passport_Status_for_Vendor_Staff_Required_for_international_projects:
              ["Clean Passport", "Passport Under Process", "Not Ready"],
          },
        },
        {
          name: "Crewel - Embroidery Curtains",
          id: "crewel_embroi",
          details: {
            material_type: [
              "Organic Cotton",
              "Kashmir Silk",
              "Velvet",
              "Organic Linen",
            ],
            embroidery_stitch_techniques: [
              "Chain Stitch",
              "Satin Stitch",
              "Blanket Stitch",
              "Stem Stitch",
              "Chain Stitch (Split Variation)",
              "Herringbone Stitch",
              "Couching Stitch",
              "Flat Stitch",
              "Raised Chain Stitch",
              "French Knots",
            ],
            design_pattern_types: [
              "Paisley Motifs",
              "Birds and Animals",
              "Scenic Landscape ",
              "Floral Designs ",
              "Geometric Patterns",
              "Abstract Themes ",
              "Traditional Motifs ",
              "Seasonal Themes",
            ],
            overlocked_edges: [
              "Standard Overlock",
              "Rolled Hem Overlock",
              "Flatlock Overlock",
              "Decorative Overlock",
              "Blind Hem Overlock",
              "None",
            ],
            weighted_hem: [
              "Standard Weighted Hem",
              "Continuous Weighted Hem",
              "Corner-Only Weights",
              "Chain Weighted Hem",
              "Magnetic Weighted Hem",
              "None",
            ],
            curtain_lining: [
              "Standard Lining",
              "Blackout Lining",
              "Thermal Lining",
              "Interlining",
              "Sheer or Voile Lining",
              "Soundproof Lining",
              "Waterproof Lining",
              "None",
            ],
            certifications: [
              "GI Certifications",
              "GOTS",
              "OEKO-TEX® Standard 100",
              "REACH",
              "BCI",
              "SA8000",
              "ISO 14001",
              "Cradle to Cradle",
              "None",
            ],
            color_shades: [
              "Neutrals",
              "Blues",
              "Greens",
              "Yellows and Golds",
              "Browns",
              "Reds and Burgundies",
              "Pastels",
            ],
            embellishments: [
              "Trims and Tassels",
              "Beading",
              "Pom-Pom Trim",
              "Fringe",
              "Grommets and Decorative Rings",
              "Appliqué Patterns",
              "Crystal or Gem Accents",
              "Metallic Threading or Accents",
              "Tiebacks with Embellished Details",
            ],
            product_name_and_dimensions: [
              "Curtain Panel: 137 cm x 213 cm",
              "Extra Long Panel: 137 cm x 274 cm",
              "Floor-to-Ceiling Panel: 137 cm x 244 cm",
              "Café Curtain Panel: 76 cm x 91 cm",
              "Valance: 46 cm x 183 cm",
              "Tie-Up Shade: 107 cm x 160 cm",
              "Short Panel: 61 cm x 61 cm",
              "Bay Curtain: 91 cm x 152 cm (per panel)",
              "Sliding Door Panel: 183 cm x 203 cm",
              "Window Scarf: 51 cm x 366 cm",
              "Standard Shower Curtain: 183 cm x 183 cm",
              "Long Shower Curtain: 183 cm x 213 cm",
              "Wide Shower Curtain: 274 cm x 183 cm",
              "Corner Shower: 183 cm x 183 cm (per side)",
              "Curved Shower: 183 cm x 183 cm",
            ],
          },
        },
      ],
    },
    {
      name: "Recycled Craft",
      id: "cat8",
      subcategories: [
        { name: "Papier-Mache", id: "papier-machie" },
        { name: "Gabba", id: "gabba" },
      ],
    },
    {
      name: "Sports Craft",
      id: "cat9",
      subcategories: [
        {
          name: "Circket-Bat",
          id: "circketBag",
          details: {
            material_type: [" Willow Wood", "Kashmir Willow"],
            production_process: [" Handcrafted", "Machine-made"],
            design_pattern_types: [" Traditional Bat Design", "Custom Design"],
            dimensions: [
              'Men’s: Length: 33", Width: 4.5"',
              'Women’s: Length: 32" , Width: 4.25"',
              'Youth : Length: 30", Width: 4"',
            ],
            certifications: [
              "GI Certifications",
              "GOTS",
              "OEKO-TEX® Standard 100",
              "REACH",
              "BCI",
              "SA8000",
              "ISO 14001",
              "Cradle to Cradle",
              "None",
            ],
            color_shades: ["Natural Wood Finish", "Custom Colors"],
            finishing_techniques: [
              "Hand-polished",
              "Custom Varnish Finish",
              "Sanding",
            ],
            weight: [
              "Light (Suitable for beginners or young players)",
              "Medium (Ideal for general use)",
              "Heavy (Preferred by professional players for added power)",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Chess-Board",
          id: "chess-board",
          details: {
            material_type: ["Wood (e.g., Walnut, Maple)"],
            production_process: [" Handcrafted", "Machine-made"],
            design_pattern_types: [
              "Traditional Chess Patterns (Classic Squares)",
              "Custom Design",
            ],
            dimensions: [
              'Standard Chess Board: Length/Width: 16" x 16"',
              'Tournament Size Chess Board: Length/Width: 20" x 20"',
              'Small Travel Chess Board: Length/Width: 12" x 12"',
            ],
            certifications: [
              "GI Certifications",
              "GOTS",
              "OEKO-TEX® Standard 100",
              "REACH",
              "BCI",
              "SA8000",
              "ISO 14001",
              "Cradle to Cradle",
              "None",
            ],
            color_shades: ["Earthy Wood Shades", "Walnut", "Oak", "Maple"],
            finishing_techniques: [
              " Hand-polished for smooth surface and longevity",
              "Wood-stained or lacquered for protection",
            ],
            weight: [
              " Light (Portable and ideal for travel)",
              "Medium (Standard size for playing)",
              "Heavy (Luxury or tournament quality)",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
      ],
    },
    {
      name: "Hide Craft",
      id: "cat10",
      subcategories: [
        {
          name: "Leather",
          id: "leather",
          details: {
            material_type: ["Full-grain Leather", "Top-grain Leather", "Suede"],
            production_process: ["Handcrafted", "Machine-made"],
            design_pattern_types: [
              "Traditional Patterns (e.g., embossing, tooling)",
              "Modern Patterns (e.g., minimalistic designs, laser engraving)",
              "Custom Design",
            ],
            product_line: [
              " Leather Accessories: Wallets, Belts, Bags, Keychains",
              "Leather Garments: Jackets, Gloves, Shoes",
              "Leather Upholstery: Furniture, Car Seats",
              "Leather Crafting Kits: Tools, Materials",
            ],
            color_shades: [
              "Earthy Tones: Brown, Tan, Beige",
              "Dark Shades: Black, Charcoal, Deep Burgundy",
            ],
            finishing_techniques: [
              "Waxed for a smooth and shiny surface",
              "Stained or dyed to enhance color depth and richness",
              "Natural Leather Finish for a rustic look",
            ],
            weight: [
              "Light (Soft leather, ideal for garments)",
              "Medium (Standard leather for accessories)",
              "Heavy (Durable leather for bags, belts, etc.)",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
        {
          name: "Fur & Astrakhan",
          id: "astrakhan",
          details: {
            material_type: [
              "Natural Fur (e.g., Mink, Fox)",
              "Faux Fur",
              "Astrakhan (Karakul Lamb Fur)",
            ],
            production_process: ["Handcrafted", "Machine-made"],
            design_pattern_types: [
              "Classic Fur Patterns (e.g., solid color, natural fur textures)",
            ],
            product_line: [
              " Fur Garments: Coats, Jackets, Gloves, Hats",
              "Fur Accessories: Scarves, Shawls, Stoles, Capes",
              "Fur Trim: For custom garments and home décor",
              "Astrakhan Products: Outerwear, Blankets, Cushions",
            ],
            color_shades: [
              "Natural Fur Colors: Brown, White, Black, Grey",
              "Dyed Fur: Burgundy, Blue, Purple",
            ],
            finishing_techniques: [
              "Fur Brushed for smoothness and volume",
              "Curled or Crimped for added texture",
              "Dyed for vibrant and customized colors",
            ],
            weight: [
              " Light (Ideal for garments like fur coats or scarves)",
              "Medium (Standard fur for fashion accessories)",
              "Heavy (Luxury fur for outerwear and blankets)",
            ],
            packaging: [
              "Custom-fit Crates/Boxes",
              "Eco-friendly Packaging Materials ",
            ],
            vendor_able_to_handle_product_labeling: [
              "Dimensions Label",
              "Weight Label",
              "Wood Type Identification Label",
              "Handling Instructions Label",
              "QR Code or Barcode",
            ],
            logistics: [
              "Local Delivery (via local courier services)",
              "International Shipping (via DHL/FedEx)",
            ],
            vendor_able_to_handle_following_services_on_DKC_platform: [
              "Measurement Guidance",
              "Calculation Tools",
              "Customer Consultations",
              "Custom Design Services",
              "Interior Consultation",
            ],
          },
        },
      ],
    },
    {
      name: "Culinary Craft",
      id: "cat11",
      subcategories: [
        { name: "Wazwan", id: "wazwan" },
        { name: "Kahwa & Pink Tea", id: "kahwa" },
      ],
    },
    {
      name: "Embriodery",
      id: "cat12",
      subcategories: [
        { name: "Sozni-Fine Work", id: "sozni" },
        { name: "Tilla-Matallic", id: "tilla" },
        { name: "Crewel-Hook", id: "crewelHook" },
        { name: "Aari-Chain Stitch", id: "aari" },
        { name: "Papier-Machie Inspired Embriodery", id: "crewelHook" },
      ],
    },
  ];
  const {
    selectedCategories,
    selectedSubcategories,
    selectedValues,
    toggleCategory,
    selectAllCategories,
    clearAllCategories,
    toggleSubcategory,
    toggleCategoryExpansion,
    expandedCategories,
    handleSelection,
    clearAllSubcategories,
    selectAllSubcategories,
    expandMainCategory,
    toggleMainCategoryExpansion
  } = useCategoryHandlers(categories);

  return (
    <div className="container mt-5">
      <CategorySelector
        categories={categories}
        selectedCategories={selectedCategories}
        toggleCategory={toggleCategory}
        selectAllCategories={selectAllCategories}
        clearAllCategories={clearAllCategories}
        expandMainCategory={expandMainCategory}
        toggleMainCategoryExpansion={toggleMainCategoryExpansion}
      />
      <SubcategorySelector
        selectedCategories={selectedCategories}
        categories={categories}
        toggleSubcategory={toggleSubcategory}
        expandedCategories={expandedCategories}
        toggleCategoryExpansion={toggleCategoryExpansion}
        selectedSubcategories={selectedSubcategories}
        clearAllSubcategories={clearAllSubcategories}
        selectAllSubcategories={selectAllSubcategories}
      />
      <DetailsRenderer
        selectedSubcategories={selectedSubcategories}
        categories={categories}
        selectedValues={selectedValues}
        handleSelection={(key, value) => handleSelection(key, value)}
      />
    </div>
  );
};

export default ProductionPortfolio;
